version: "3"
##
## instalar fontes do windows no linux
## sudo apt-get install ttf-mscorefonts-installer
##
networks:
    local:

services:
    web:
        image: nginx
        container_name: web-proxy
        volumes:
            # - ./web/nginx.conf:/etc/nginx/nginx.conf
            - ./web/www/:/usr/share/nginx/html/
        command: [nginx-debug, '-g', 'daemon off;']
        ports:
            - 8080:80
        environment:
            TZ: "America/Sao_Paulo"
        networks:
            - local
    alex:
        image: nginx
        container_name: web-alex
        volumes:
            # - ./alex/nginx.conf:/etc/nginx/nginx.conf
            - ./alex/default.conf:/etc/nginx/conf.d/default.conf
            - ./alex/www/:/usr/share/nginx/html/
        command: [nginx-debug, '-g', 'daemon off;']
        ports:
            - 8081:80
        environment:
            TZ: "America/Sao_Paulo"
        networks:
            - local
