version: "3"
##
## instalar fontes do windows no linux
## sudo apt-get install ttf-mscorefonts-installer
##

services:
    web:
        image: nginx
        container_name: web-proxy
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
            - ./nginx/:/usr/share/nginx/html/
        command: [nginx-debug, '-g', 'daemon off;']
        ports:
            - 80:80
            - 443:443
        environment:
            TZ: "America/Sao_Paulo"
